service: radar180

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  # single run function to be invoked locally - fills local database with game data
  ingest-games:
    handler: src/functions/ingest.retrieveAndStoreGames
  
  # retrieves teams - currently attaches game data and bye weeks
  retrieve-teams:
    handler: src/functions/teams.retrieve
    events:
      - http:
          path: /teams
          method: get
          cors: true
  
  # retrieve the team average scores
  retrieve-team-scores:
    handler: src/functions/teams.retrieveSeasonAvg
    events:
      - http:
          path: /teams/season_avg
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript